backend/urls.py
from django.contrib import admin # type: ignore
from django.urls import path, include # type: ignore

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontend.urls')),
    path('select2/', include('django_select2.urls')),
    path('accounts/', include('accounts.urls')),
]

frontend/urls.py
from django.urls import path  # type: ignore

from . import views

app_name = 'frontend'
urlpatterns = [
    path('', views.index, name='index'),
    path('beneficiary_list', views.beneficiary_list, name='beneficiary_list'),
    path('beneficiary/<int:pk>/', views.beneficiary_detail, name='beneficiary_detail'),
    path('beneficiary/<int:pk>/edit/', views.beneficiary_edit, name='beneficiary_edit'),
    path('payment_add/', views.payment_add, name='payment_add'),
    path('payment_add/<int:pk>/beneficiary/', views.payment_add_beneficiary, name='payment_add_beneficiary'),
    path('beneficiary/add/', views.beneficiary_add, name='beneficiary_add'),
    path('payment_list_all', views.payment_list, name='payment_list_all'),
    path('payment_detail/<int:pk>/', views.payment_detail, name='payment_detail'),
    path('export_payment_list_to_excel/<int:pk>/', views.export_payment_list_to_excel, name='export_payment_list_to_excel'),
    path('import_beneficiaries/', views.import_beneficiaries, name='import_beneficiaries'),
    path('beneficiary_list_full', views.beneficiary_list_full, name='beneficiary_list_full'),
    path('application/create/', views.application_create, name='application_create'),
    path('application/list/', views.application_list_all, name='application_list_all'),
    path('application/list/<int:benefit_id>/<int:year>/', views.application_list_detail, name='application_list_detail'),
   ]

frontend/forms.py
from django import forms # type: ignore
from .models import Beneficiary, PaymentList, PaymentListBeneficiary, Application, Benefit
from django_select2.forms import Select2MultipleWidget, Select2Widget # type: ignore
from django.forms import inlineformset_factory

class BeneficiaryForm(forms.ModelForm):
    class Meta:
        model = Beneficiary
        fields = ['first_name', 'last_name', 'place', 'bank_account_number', 'is_alive', 'version']
        labels = {
            'first_name': 'Imię',
            'last_name': 'Nazwisko',
            'place': 'Placówka',
            'bank_account_number': 'Nr rachunku bankowego',
            'is_alive': 'Czy aktywny?',
        }
        widgets = {'version': forms.HiddenInput()}
    version = forms.IntegerField(widget=forms.HiddenInput())

class PaymentListForm(forms.ModelForm):
    class Meta:
        model = PaymentList
        fields = ['name']
        labels = {'name': 'Nazwa Listy Wypłat'}

class PaymentListBeneficiaryForm(forms.ModelForm):
    beneficiary = forms.ModelChoiceField(queryset=Beneficiary.objects.filter(is_alive=True), widget=Select2Widget(attrs={'data-minimum-input-length': 0}))
    amount = forms.DecimalField(max_digits=10, decimal_places=2)

    class Meta:
        model = PaymentListBeneficiary
        fields = ['beneficiary', 'amount']
        labels = {'amount': 'Kwota'}

class NewBeneficiaryForm(forms.ModelForm):
     class Meta:
          model = Beneficiary
          fields = ['first_name', 'last_name', 'place', 'bank_account_number',]
          labels = {'first_name': 'Imię',
                    'last_name': 'Nazwisko', 
                    'place': 'Placówka', 
                    'bank_account_number':'Nr Konta Bankowego', 
                    }
          widgets = {'first_name': forms.TextInput(),
                     'last_name': forms.TextInput(),
                     'place':  forms.TextInput(),
                     'bank_account_number': forms.TextInput(),
                     }

class UploadFileForm(forms.Form):
    file = forms.FileField(label='Wybierz plik Excel')

class ApplicationForm(forms.ModelForm):
    beneficiary = forms.ModelChoiceField(queryset=Beneficiary.objects.filter(is_alive=True), widget=Select2Widget(attrs={'data-minimum-input-length': 0}))
    class Meta:
        model = Application
        fields = ['beneficiary', 'benefit', 'monthly_income', 'household_type']
        labels = {'beneficiary': 'beneficjent',
                  'benefit': 'Świadczenie',
                  'monthly_income': 'Średni dochód brutto na osobę z ostanich 3 miesięcy',
                  'household_type':'Typ gospodarstwa domowego:'}

    def __init__(self, *args, **kwargs):
        super(ApplicationForm, self).__init__(*args, **kwargs)
        self.fields['benefit'].queryset = Benefit.objects.all()

class PaymentListBulkEditForm(forms.Form):
    amount = forms.DecimalField(max_digits=10, decimal_places=2)
    beneficiaries = forms.ModelMultipleChoiceField(queryset=Beneficiary.objects.all())

class PaymentListBeneficiaryForm(forms.ModelForm):
    class Meta:
        model = PaymentListBeneficiary
        fields = ['beneficiary', 'amount']

PaymentListBeneficiaryFormSet = inlineformset_factory(
    PaymentList, PaymentListBeneficiary, form=PaymentListBeneficiaryForm, extra=0
)

class PaymentListBeneficiaryForm(forms.ModelForm):
    class Meta:
        model = PaymentListBeneficiary
        fields = ['beneficiary', 'amount']

frontend/views.py
from django.shortcuts import render, get_object_or_404, redirect # type: ignore
from .models import Beneficiary, PaymentList, PaymentHistory, PaymentListBeneficiary, Application, Benefit, ApplicationList
from .forms import BeneficiaryForm, PaymentListForm, NewBeneficiaryForm, PaymentListBeneficiaryForm, UploadFileForm, ApplicationForm, PaymentListBulkEditForm, PaymentListBeneficiaryFormSet
from django.db.models import Q # type: ignore
from django.core.paginator import Paginator  # type: ignore # Import Paginator
from django.contrib.auth.decorators import login_required # type: ignore
from django.forms import inlineformset_factory # type: ignore
from django.core.exceptions import ValidationError # type: ignore
import openpyxl # type: ignore
from openpyxl.utils import get_column_letter # type: ignore
from django.http import HttpResponse # type: ignore
from io import BytesIO
from django.contrib import messages # type: ignore
from django.db import transaction, IntegrityError # type: ignore
from .tables import PaymentListBeneficiaryTable

def index(request): #zdefiniowanie strony index
    return render(request, 'frontend/index.html')



#Widoki dotyczące beneficjentów 
@login_required
def beneficiary_list(request):
    query = request.GET.get('q')
    if query:
        beneficiaries = Beneficiary.objects.filter(
            Q(first_name__icontains=query) | 
            Q(last_name__icontains=query) | 
            Q(place__icontains=query)
        )
    else:
        beneficiaries = Beneficiary.objects.all()

    active_count = Beneficiary.objects.filter(is_alive=True).count()
    inactive_count = Beneficiary.objects.filter(is_alive=False).count()
    
    paginator = Paginator(beneficiaries, 50)  # 50 beneficjentów na stronę
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    
    return render(request, 'frontend/beneficiary_list.html', {'page_obj': page_obj, 'active_count':active_count, 'inactive_count':inactive_count})

@login_required
def beneficiary_add(request): #zdefiniowanie manualnego dodawania użytkowników 
    if request.method != 'POST':
        form = NewBeneficiaryForm()
    else:
        form = NewBeneficiaryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('frontend:beneficiary_add')
    return render(request, 'frontend/beneficiary_add.html', {'form':form})

@login_required
def beneficiary_detail(request, pk):
    beneficiary = get_object_or_404(Beneficiary, pk=pk)
    payment_history = PaymentHistory.objects.filter(beneficiary=beneficiary)
    return render(request, 'frontend/beneficiary_detail.html', {'beneficiary': beneficiary, 'payment_history': payment_history})

@login_required
def import_beneficiaries(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            file = request.FILES['file']
            wb = openpyxl.load_workbook(file)
            sheet = wb.active
            skipped_beneficiaries = []

            for row in sheet.iter_rows(min_row=2, values_only=True):
                first_name, last_name, place, bank_account_number = row
                if Beneficiary.objects.filter(first_name=first_name, last_name=last_name, place=place).exists():
                    skipped_beneficiaries.append(f'{first_name} {last_name} ({place})')
                    continue

                Beneficiary.objects.create(
                    first_name=first_name,
                    last_name=last_name,
                    place=place,
                    bank_account_number=bank_account_number,)

            if skipped_beneficiaries:
                messages.warning(request, f'Import przebiegł pomyślnie, pominięci zostali następujący beneficjenci: {", ".join(skipped_beneficiaries)}')
            else:
                messages.success(request, 'Pomyślnie zaimportowano wszystkich beneficjentów')

            return redirect('frontend:beneficiary_list')
    else:
        form = UploadFileForm()
    return render(request, 'frontend/import_beneficiaries.html', {'form': form})

@login_required
def beneficiary_edit(request, pk):
    beneficiary = get_object_or_404(Beneficiary, pk=pk)
    
    if request.method == 'POST':
        form = BeneficiaryForm(request.POST, instance=beneficiary)
        if form.is_valid():
            with transaction.atomic():
                if Beneficiary.objects.filter(pk=pk, version=form.cleaned_data['version']).exists():
                    beneficiary = form.save(commit=False)
                    beneficiary.version += 1
                    beneficiary.save()
                    messages.success(request, 'Beneficjent został pomyślnie zaktualizowany.')
                    return redirect('frontend:beneficiary_detail', pk=beneficiary.pk)
                else:
                    form.add_error(None, 'Ten rekord został już zaktualizowany przez innego użytkownika.')
    else:
        form = BeneficiaryForm(instance=beneficiary)
        form.fields['version'].initial = beneficiary.version
    
    return render(request, 'frontend/beneficiary_edit.html', {'form': form, 'beneficiary': beneficiary})

def beneficiary_list_full(request):
    query = request.GET.get('q')
    if query:
        beneficiaries = Beneficiary.objects.filter(
            Q(first_name__icontains=query) | 
            Q(last_name__icontains=query) | 
            Q(place__icontains=query)
        )
    else:
        beneficiaries = Beneficiary.objects.all()

    active_count = Beneficiary.objects.filter(is_alive=True).count()
    inactive_count = Beneficiary.objects.filter(is_alive=False).count()
    
    paginator = Paginator(beneficiaries, 50)  # 50 beneficjentów na stronę
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    
    return render(request, 'frontend/beneficiary_list_full.html', {'page_obj': page_obj, 'active_count':active_count, 'inactive_count':inactive_count})


#Widoki dotyczące wniosków 
#potrzebuję najpierw stworzyć model wniosku, wniosek musi być dodawany do 






@login_required
def payment_add(request):
    if request.method == 'POST':
        form = PaymentListForm(request.POST)
        if form.is_valid():
            payment_list = form.save()
            return redirect('frontend:payment_add_beneficiary', pk=payment_list.pk)
    else:
        form = PaymentListForm()
    return render(request, 'frontend/payment_add.html', {'form': form})

def payment_add_beneficiary(request, pk):
    payment_list = get_object_or_404(PaymentList, pk=pk)
    
    if request.method == 'POST':
        form = PaymentListBeneficiaryForm(request.POST)
        if form.is_valid():
            payment_beneficiary = form.save(commit=False)
            payment_beneficiary.payment_list = payment_list
            
            beneficiary = payment_beneficiary.beneficiary
            
            # Sprawdzenie, czy beneficjent jest żywy
            if not beneficiary.is_alive:
                form.add_error('beneficiary', 'Ten beneficjent nie żyje i nie może być dodany do listy wypłat.')
            elif PaymentListBeneficiary.objects.filter(payment_list=payment_list, beneficiary=beneficiary).exists():
                form.add_error('beneficiary', 'Ten beneficjent już istnieje na tej liście wypłat.')
            else:
                payment_beneficiary.save()
                PaymentHistory.objects.create(
                    beneficiary=beneficiary,
                    payment_list=payment_list,
                    amount=payment_beneficiary.amount
                )
                messages.success(request, f'Beneficjent {beneficiary} został dodany do listy wypłat.')
                return redirect('frontend:payment_add_beneficiary', pk=payment_list.pk)
    else:
        form = PaymentListBeneficiaryForm()
    
    return render(request, 'frontend/payment_add_beneficiary.html', {'form': form, 'payment_list': payment_list})

@login_required
def payment_detail(request, pk):
    payment = get_object_or_404(PaymentList, pk=pk)
    payment_list_beneficiaries = PaymentListBeneficiary.objects.filter(payment_list=payment)
    
    beneficiaries = [
        {
            "first_name": plb.beneficiary.first_name,
            "last_name": plb.beneficiary.last_name,
            "place": plb.beneficiary.place,
            "bank_account_number": plb.beneficiary.bank_account_number,
            "amount": plb.amount
        }
        for plb in payment_list_beneficiaries
    ]
    
    return render(request, 'frontend/payment_detail.html', {'payment': payment, 'beneficiaries': beneficiaries})

@login_required
def payment_list(request):
    payments = PaymentList.objects.all()
    return render(request, 'frontend/payment_list.html', {'payments': payments})

@login_required
def export_payment_list_to_excel(request, pk):
    payment_list = get_object_or_404(PaymentList, pk=pk)
    payment_list_beneficiaries = PaymentListBeneficiary.objects.filter(payment_list=payment_list)

    # Create a workbook and a worksheet
    workbook = openpyxl.Workbook()
    worksheet = workbook.active
    worksheet.title = payment_list.name

    # Define the titles for columns
    columns = ['rachunek obcy', 'nr konta', 'imie i nazwisko', 'kwota', 'Tytuł', 'data']
    row_num = 1

    # Assign the titles for each cell of the header
    for col_num, column_title in enumerate(columns, 1):
        cell = worksheet.cell(row=row_num, column=col_num)
        cell.value = column_title

    # Fill the worksheet with data
    for plb in payment_list_beneficiaries:
        row_num += 1
        worksheet.cell(row=row_num, column=1, value=f"9512401037111001109117246")
        worksheet.cell(row=row_num, column=3, value=f"{plb.beneficiary.first_name} {plb.beneficiary.last_name}")
        worksheet.cell(row=row_num, column=2, value=plb.beneficiary.bank_account_number)

frontend/templates/frontend/application_form.html
{% extends "frontend/base.html" %}

{% block content %}
<h2>Dodaj Wniosek</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Zapisz</button>
</form>

<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet" />

<script>
    $(document).ready(function() {
        $('select').select2();
    });
</script>
{% endblock %}

frontend/templates/frontend/application_list_all.html
{% extends "frontend/base.html" %}

{% block content %}
<h2>Wszystkie wnioski</h2>
<ul>
    {% for application_list in application_lists %}
    <li>
        <a href="{% url 'frontend:application_list_detail' application_list.benefit.id application_list.year %}">
            {{ application_list.benefit.name }} {{ application_list.year }}
        </a>
    </li>
    {% endfor %}
</ul>
{% endblock %}

frontend/templates/frontend/application_list_detail.html
{% extends "frontend/base.html" %}

{% block content %}
<h2>{{ application_list.benefit.name }} {{ application_list.year }}</h2>
<form method="post">
    {% csrf_token %}
    <ul>
        {% for application in applications %}
        <li>
            <input type="checkbox" name="applications" value="{{ application.id }}"> {{ application.beneficiary }} - {{ application.benefit }} - {{ application.monthly_income }} - {{ application.household_type }}
        </li>
        {% endfor %}
    </ul>
    <button type="submit">Zatwierdź</button>
</form>
{% endblock %}

frontend/templates/frontend/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta charset="UTF-8">
        <title>Strona</title>
        {% load static %}
        <link href="{% static 'css/style.css' %}" rel="stylesheet" />
        <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
    </head>
    <body class="body">
        <header class="header">
            <div class="navbar">
                <a href="{% url 'frontend:index' %}">Strona główna</a>
                <a href="{% url 'frontend:payment_add' %}">Utwórz liste wypłat</a>
                <a href="{% url 'frontend:beneficiary_list' %}">Lista beneficjentów</a> 
                <a href="{% url 'frontend:payment_list_all' %}">Wszystkie listy wypłat</a>
                <a href="{% url 'frontend:application_create' %}">Dodaj Wniosek</a>
                <a href="{% url 'frontend:application_list_all' %}">Lista Wniosków</a>
                    {% if user.is_authenticated %}
                    <p>Witaj, {{ user.username }}.</p>
                    {% else %}
                    <a href='{% url 'login' %}'>Zaloguj</a>
                    {% endif %}
                    {% if user.is_authenticated %}
                    <form action="{% url 'logout' %}" method="post">
                    {% csrf_token %}
                    <button name="submit">Wyloguj</button>
                    </form>
                    {% endif %}

            </div> 
        </header>
    
        <div class="maindiv">
            {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
         {% endif %}
            {% block content %}
            {% endblock content %}
        </div>

        <footer class="footer">
            <p>Autorką aplikacji jest Wiktoria Vizera Kowalska</p>
        </footer> 
    </body>
</html>

frontend/templates/frontend/beneficiary_add.html
{% extends "frontend/base.html" %}

{% block content %}

<p>Dodaj nowego beneficjenta</p>
<form  method='post' style="border-style:dotted; border-color: purple; border-radius: 3px;">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Dodaj beneficjenta</button>
</form>
{% endblock content %}

frontend/templates/frontend/beneficiary_detail.html
{% extends "frontend/base.html" %}

{% block content %}
<div>
    <h1>{{ beneficiary.first_name }} {{ beneficiary.last_name }}</h1>
    <p>Placówka: {{ beneficiary.place }}</p>
    <p>Nr Konta Bankowego: {{ beneficiary.bank_account_number }}</p>
    <p>data urodzenia: {{ beneficiary.birth_date }}</p>
    <p>Adres: {{ beneficiary.place_of_residence }}</p>
    <p>Numer tel: {{ beneficiary.phone_num }}
    </p>
    {% if beneficiary.is_alive %}</p>
    <p>Beneficjent aktywny</p>
    {% else %}
    <p>Beneficjent nieaktywny</p>
    {% endif %}
    <h2>Historia wypłat:</h2>
    <ul>
        {% for entry in payment_history %}
        <li>{{ entry.payment_list.name }} - {{ entry.date_added }} - {{ entry.amount }}</li>
            {% endfor %}
    </ul>
    <div class="beneficiary_add">
        <a href="edit">Edytuj beneficjenta</a>
    </div>
</div>
{% endblock content %}

frontend/templates/frontend/beneficiary_edit.html
{% extends "frontend/base.html" %}

{% block content %}
<h1>Edytuj Beneficjenta: {{ beneficiary.first_name }} {{ beneficiary.last_name }}</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Zapisz zmiany</button>
</form>
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
{% endblock %}

frontend/templates/frontend/beneficiary_list.html
{% extends "frontend/base.html" %}

{% block content %}
    <b>Lista beneficjentów zarejestrowanych w systemie</b>
    <form method="GET" action="">
        <input type="text" name="q" placeholder="Szukaj...">
        <button type="submit">Szukaj</button>
    </form>
    <div class="beneficiary_list">
    <ul >
        {% for beneficiary in page_obj %}
            <li>
                <a href="{% url 'frontend:beneficiary_detail' beneficiary.pk %}"><table border="1"><tr><td>{{ beneficiary.first_name }}</td><td>{{ beneficiary.last_name }}</td><td>{{ beneficiary.place }}</td></tr></table></a>
            </li>
        {% endfor %}
    </ul>
    </div>
    <div class="beneficiary_add">
        {% if page_obj.has_previous %}
            <a href="?{% if request.GET.q %}q={{ request.GET.q }}&{% endif %}page=1">&laquo; Pierwsza</a>
            <a href="?{% if request.GET.q %}q={{ request.GET.q }}&{% endif %}page={{ page_obj.previous_page_number }}">Poprzednia</a>
        {% endif %}
        <a>Strona {{ page_obj.number }} z {{ page_obj.paginator.num_pages }}.</a>
        {% if page_obj.has_next %}
            <a href="?{% if request.GET.q %}q={{ request.GET.q }}&{% endif %}page={{ page_obj.next_page_number }}">Następna</a>
            <a href="?{% if request.GET.q %}q={{ request.GET.q }}&{% endif %}page={{ page_obj.paginator.num_pages }}">Ostatnia&raquo;</a>
        {% endif %}
        <a href="beneficiary/add">Dodaj nowego beneficjenta</a>
        <a href="import_beneficiaries">Importuj z pliku</a>
        <a>Aktywni beneficjenci:{{ active_count }}</a>
        <a>Nieaktywni {{ inactive_count }}</a>
        
    </div>
{% endblock content %}

frontend/templates/frontend/beneficiary_list_full.html
{% block content %}
    <b>Lista beneficjentów zarejestrowanych w systemie</b>
    <form method="GET" action="">
        <input type="text" name="q" placeholder="Szukaj...">
        <button type="submit">Szukaj</button>
    </form>
    <div class="beneficiary_list">
    <ul >
        {% for beneficiary in page_obj %}
            <li>
                <a href="{% url 'frontend:beneficiary_detail' beneficiary.pk %}"><table border="1"><tr><td>{{ beneficiary.first_name }}</td><td>{{ beneficiary.last_name }}</td><td>{{ beneficiary.place }}</td></tr></table></a>
            </li>
        {% endfor %}
    </ul>
    </div>
    <div class="beneficiary_add">
        {% if page_obj.has_previous %}
            <a href="?{% if request.GET.q %}q={{ request.GET.q }}&{% endif %}page=1">&laquo; Pierwsza</a>
            <a href="?{% if request.GET.q %}q={{ request.GET.q }}&{% endif %}page={{ page_obj.previous_page_number }}">Poprzednia</a>
        {% endif %}
        <a>Strona {{ page_obj.number }} z {{ page_obj.paginator.num_pages }}.</a>
        {% if page_obj.has_next %}
            <a href="?{% if request.GET.q %}q={{ request.GET.q }}&{% endif %}page={{ page_obj.next_page_number }}">Następna</a>
            <a href="?{% if request.GET.q %}q={{ request.GET.q }}&{% endif %}page={{ page_obj.paginator.num_pages }}">Ostatnia&raquo;</a>
        {% endif %}
        <a href="beneficiary/add">Dodaj nowego beneficjenta</a>
        <a href="import_beneficiaries">Importuj z pliku</a>
        <a>Aktywni beneficjenci:{{ active_count }}</a>
        <a>Nieaktywni {{ inactive_count }}</a>
        
    </div>
{% endblock content %}

frontend/templates/frontend/import_beneficiaries.html
{% extends "frontend/base.html" %}

{% block content %}
<h1>Importuj Beneficjentów z Pliku Excel</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Importuj</button>
</form>
{% endblock %}

frontend/templates/frontend/index.html
{% extends "frontend/base.html" %}

{% block content %}
    <h1>Startowa strona testowa</h1>
    <p>Do zrobienia</p>
    <ul style="text-align: left;">
        <li>dodać rejestracje i logowanie(jest) dla użytkowników</li>
        <li>dodać transakcje (blokade edycji rekordu podczas edycji tego rekordu w momencie gdy inny użytkownik edytuje)(zrobione)</li>
        <li>dodać import z excela(zrobione)</li>
        <li>dodać wyświetlanie listy wypłat (jest)</li>
        <li>dodać export listy wypłat (zrobione)</li>
        <li>dodać komórkę czy dany beneficjent żyje, jeśli nie żyje to nie można dodać do listy wypłat (zrobione)</li>
        <li>dodać adres zamieszkania, data urodzenia</li>
        <li>dodać wnioski, data złożenia wniosku, i jaki wniosek</li>
        <li>Emeryci - grusza, zapomoga, porzyczka mieszkaniowa, wycieczki</li>
        <li>pracownicy czynni - grusza</li>
        <li>protokół imie nazwisko adres</li>
    </ul>
{% endblock content %}

frontend/templates/frontend/payment_add_beneficiary.html
{% extends "frontend/base.html" %}

{% block content %}
<h1>Dodaj beneficjentów do {{ payment_list.name }}</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Dodaj beneficjenta</button>
</form>
<a href="{% url 'frontend:payment_list_all' %}">Zakończ dodawanie beneficjentów</a>

<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet" />

<script>
    $(document).ready(function() {
        $('select').select2();
    });
</script>
{% endblock %}

frontend/templates/frontend/payment_detail.html
{% extends "frontend/base.html" %}

{% block content %}
<div>
    <h1>{{ payment.name }}</h1>
    <h2>Lista Osób na tej liście </h2>
    <table style="margin: auto;" border="1">
        <tr><td>Imię</td>  <td>Nazwisko</td><td>Nr konta bankowegoooooooooo</td><td>Placówka</td><td>Kwota</td></tr>
        {% for entry in beneficiaries %}
        <tr><td>{{ entry.first_name }}</td>  <td>{{ entry.last_name }}</td><td>{{ entry.bank_account_number }}</td><td>{{ entry.place }}</td><td>{{ entry.amount }}</td></tr>
         {% endfor %}
    </table>
    <a href="{% url 'frontend:export_payment_list_to_excel' payment.pk %}">Export to Excel</a>
</div>
{% endblock content %}

frontend/templates/frontend/payment_list.html
{% extends "frontend/base.html" %}

{% block content %}
    <h1>Listy wypłat</h1>
    <div class="payment_list">
        <ul>
        {% for payment in payments %}
                <li><a href="{% url 'frontend:payment_detail' payment.pk %}"><table style="margin:auto;" border="1"><tr><td>{{ payment.name }}</td><td>{{ payment.date_added }}</td></tr></table></a></li>
        {% endfor %}
        </ul>
    </div> 
{% endblock content %}